apiVersion: apps/v1
kind: Deployment
metadata:
  name: allisonmerrick-cit-270
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: allisonmerrick-cit-270
  template:
    metadata:
      name: allisonmerrick-cit-270
      labels:
        app: allisonmerrick-cit-270
    spec:
      containers:
      - name: allisonmerrick-cit-270
        image: allisonmerrick/cit-270
        volumeMounts:
        - name: ssl
          mountPath: "/usr/src/app/SSL"
        command: ["npm"]
        args: ["run", "start"]
        env:
        - name: REDIS_PASS
          valueFrom:
            secretKeyRef:
              name: redis-secrets-allison
              key: REDIS_PASS
        resources:
          requests:
            cpu: 0.125
            memory: 500Mi
          limits:
            cpu: 0.125
            memory: 600Mi
        imagePullPolicy: Always
      volumes:
      - name: ssl
        secret: 
          secretName: ssl.secret.allisonmerrick
---
apiVersion: v1
kind: Service
metadata:
  name: allisonmerrick-cit-270-loadbalancer
spec:
  selector:
    app: allisonmerrick-cit-270
  type: LoadBalancer
  ports:
  - port: 443
    targetPort: 443